@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.problem.salestax.test.ProductTaxCalculatorTest#is_Able_To_Calculate_Tax_TotalCost_For_Non_Imported_Item()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.problem.salestax.test.ProductTaxCalculatorTest",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_309542241 { 
   	label=problem
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_151715214 { 
   	label=salestax
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1088267204 { 
   	label=Product
	labeljust=l
	fillcolor=white
	style=filled
   
   Product98274725XXXprice0[
	label="+ price()"
	style=filled
	fillcolor=white
	tooltip="Product

null"
	fontcolor=darkgreen
];

Product98274725XXXproductType0[
	label="+ productType()"
	style=filled
	fillcolor=white
	tooltip="Product

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1352565453 { 
   	label=ImportDutySalesTax
	labeljust=l
	fillcolor=white
	style=filled
   
   ImportDutySalesTax98274725XXXisApplicable1355179215[
	label="+ isApplicable()"
	style=filled
	fillcolor=white
	tooltip="ImportDutySalesTax

null"
	fontcolor=darkgreen
];

ImportDutySalesTax98274725XXXrate0[
	label="+ rate()"
	style=filled
	fillcolor=white
	tooltip="ImportDutySalesTax

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_234479910 { 
   	label=BasicSalesTax
	labeljust=l
	fillcolor=white
	style=filled
   
   BasicSalesTax98274725XXXisApplicable1355179215[
	label="+ isApplicable()"
	style=filled
	fillcolor=white
	tooltip="BasicSalesTax

null"
	fontcolor=darkgreen
];

BasicSalesTax98274725XXXrate0[
	label="+ rate()"
	style=filled
	fillcolor=white
	tooltip="BasicSalesTax

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_393526201 { 
   	label=ProductTaxCalculatorTest
	labeljust=l
	fillcolor=white
	style=filled
   
   ProductTaxCalculatorTest489010107XXXis_Able_To_Calculate_Tax_TotalCost_For_Non_Imported_Item0[
	label="+ is_Able_To_Calculate_Tax_TotalCost_For_Non_Imported_Item()"
	style=filled
	fillcolor=white
	tooltip="ProductTaxCalculatorTest

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_939868721 { 
   	label=ProductTaxCalculator
	labeljust=l
	fillcolor=white
	style=filled
   
   ProductTaxCalculator98274725XXXcalculateItemCost593810101[
	label="+ calculateItemCost()"
	style=filled
	fillcolor=white
	tooltip="ProductTaxCalculator

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
BasicSalesTax98274725XXXisApplicable1355179215 -> Product98274725XXXproductType0;
ProductTaxCalculator98274725XXXcalculateItemCost593810101 -> BasicSalesTax98274725XXXisApplicable1355179215;
ProductTaxCalculator98274725XXXcalculateItemCost593810101 -> BasicSalesTax98274725XXXrate0;
ProductTaxCalculator98274725XXXcalculateItemCost593810101 -> ImportDutySalesTax98274725XXXisApplicable1355179215;
ProductTaxCalculator98274725XXXcalculateItemCost593810101 -> ImportDutySalesTax98274725XXXrate0;
ProductTaxCalculator98274725XXXcalculateItemCost593810101 -> Product98274725XXXprice0;
ProductTaxCalculatorTest489010107XXXis_Able_To_Calculate_Tax_TotalCost_For_Non_Imported_Item0 -> ProductTaxCalculator98274725XXXcalculateItemCost593810101;
    
}
@enduml